import path from 'path';

const DESKTOP = 'C:\\Users\\TaiChuVan\\OneDriveNASHTECH\\Desktop';

export const DASHBOARD_PORT = 20100;

export const apps = [
  {
    id: '6gate-app',
    name: '6Gate Backend',
    group: '6gate',
    cwd: path.join(DESKTOP, '6gate', 'app'),
    command: 'npm',
    args: ['run', 'dev'],
    port: 20130,
    envFile: path.join(DESKTOP, '6gate', 'app', '.env'),
    logFile: path.join(DESKTOP, '6gate', 'app-dev.out.log'),
    errLogFile: path.join(DESKTOP, '6gate', 'app-dev.err.log'),
  },
  {
    id: '6gate-ui',
    name: '6Gate UI',
    group: '6gate',
    cwd: path.join(DESKTOP, '6gate', 'ui'),
    command: 'npm',
    args: ['run', 'dev'],
    port: 20129,
    envFile: null,
    logFile: path.join(DESKTOP, '6gate', 'ui-dev.out.log'),
    errLogFile: path.join(DESKTOP, '6gate', 'ui-dev.err.log'),
  },
  {
    id: '7router-app',
    name: '7Router Backend',
    group: '7router',
    cwd: path.join(DESKTOP, '7router'),
    command: 'pnpm',
    args: ['dev:app'],
    port: 20131,
    envFile: path.join(DESKTOP, '7router', 'app', '.env'),
    logFile: null,
    errLogFile: null,
  },
  {
    id: '7router-ui',
    name: '7Router UI',
    group: '7router',
    cwd: path.join(DESKTOP, '7router'),
    command: 'pnpm',
    args: ['dev:ui'],
    port: 20132,
    envFile: null,
    logFile: null,
    errLogFile: null,
  },
  {
    id: 'vgen-app',
    name: 'VGen Backend',
    group: 'vgen',
    cwd: path.join(DESKTOP, 'VGen'),
    command: 'pnpm',
    args: ['dev:app'],
    port: 3012,
    envFile: path.join(DESKTOP, 'VGen', 'app', '.env'),
    logFile: path.join(DESKTOP, 'VGen', 'app-dev.log'),
    errLogFile: path.join(DESKTOP, 'VGen', 'app-dev.err.log'),
  },
  {
    id: 'vgen-ui',
    name: 'VGen UI',
    group: 'vgen',
    cwd: path.join(DESKTOP, 'VGen'),
    command: 'pnpm',
    args: ['dev:ui'],
    port: 5200,
    envFile: null,
    logFile: path.join(DESKTOP, 'VGen', 'ui-dev.log'),
    errLogFile: path.join(DESKTOP, 'VGen', 'ui-dev.err.log'),
  },
  {
    id: 'meddler',
    name: 'Meddler',
    group: 'meddler',
    cwd: path.join(DESKTOP, 'Meddler'),
    command: 'npm',
    args: ['run', 'dev'],
    port: 3011,
    envFile: path.join(DESKTOP, 'Meddler', '.env'),
    logFile: path.join(DESKTOP, 'Meddler', 'dev-server.log'),
    errLogFile: path.join(DESKTOP, 'Meddler', 'dev-server.err.log'),
  },
  {
    id: 'everyminute',
    name: 'EveryMinute',
    group: 'everyminute',
    cwd: path.join(DESKTOP, 'EveryMinute'),
    command: 'npm',
    args: ['run', 'dev'],
    port: 3010,
    envFile: null,
    logFile: path.join(DESKTOP, 'EveryMinute', 'next-dev.log'),
    errLogFile: path.join(DESKTOP, 'EveryMinute', 'next-dev.err.log'),
  },
];
